import './globals.css'
import Header from './header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;800&display=swap" rel="stylesheet" />
      </head>
      <body className={` py-[50px] px-[120px] sm:px-4  sm:py-8  sm:w-max-[none]`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
